### ISSUE TITLE
[FEATURE] Container Runtime Environment

### ISSUE THREAD

**Issue by kaiehrhardt** [terramate-io/terramate#1006]
**Is your feature request related to a problem? Please describe.**

To be able to run terramate in ci, we need something like a container runtime environment.

**Describe the solution you'd like**

A Container would be nice.

**Additional context**

Difficult will probably be the dependence on terraform.

**Comment by soerenmartius** [comment]
Hi @kaiehrhardt,

Thanks for reaching out! We already provide a Docker image located at `ghcr.io/terramate-io/terramate:0.3.0`. However, I just noticed that the image is missing Git as a dependency. I just opened a PR in https://github.com/terramate-io/terramate/pull/1009 to fix this and to provide additional information on how to use the image.

**Comment by kaiehrhardt** [comment]
Hi @soerenmartius,

sorry for the unnecessary issue. I completely overlooked the image.

Thx.
