### ISSUE TITLE
[BUG]checking git default remote: remote "origin" has no default branch "main" on gitlab-ci

### ISSUE THREAD

**Issue by monegim** [terramate-io/terramate#1195]
**Describe the bug**
Running `terramate run` on different branch other than main in gitlab-ci, e.g,
```
terramate run --changed -- terraform validate
```

**To Reproduce**

1. Change a stack and commit in a branch other than `main` using `gitlab-ci`.
2. Run `terramate run` with the `--changed` option.
3. Get this error:
  ```
checking git default remote: remote "origin" has no default branch "main"
```
**Expected behavior**
Should changes be compared to the main as it is the default.

**Environment (please complete the following information):**
 - OS: Linux container
 - Gitlab Runner Type: docker
 - Host OS Version: Ubuntu 22.04
 - Terramate Version: 0.4.2

**Additional context**
When changes are pushed to the `origin/main`, it is fine, however, when changes are pushed to a different branch the error is thrown.

**Comment by mariux** [comment]
Hi @monegim,

could you please share what the following command returns for you: `git symbolic-ref refs/remotes/origin/HEAD --short`?

**Comment by monegim** [comment]
Hi @ma
Here is the result:
```
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
```
also,
```
git branch --all
* (HEAD detached at 8248f6a)
  all
  remotes/origin/main
  remotes/origin/blah
```

**Comment by monegim** [comment]
Update:

When pushed with `-u` it is ok:
```
git push -u origin blah
```
But, when pushed like:
```
git push origin blah
```
Got the mentioned error.

**Comment by monegim** [comment]
Thank you for your solution. The suggested solution solved the issue.
