### ISSUE TITLE
[FEATURE] Option for `terramate fmt` to format single file or read from `stdin`, write to `stdout`

### ISSUE THREAD

**Issue by ivenw** [terramate-io/terramate#1226]
**Is your feature request related to a problem? Please describe.**
In order to use `terramate fmt` as an autoformatter inside an editor like neovim, we need a command line option to either only pass a single file in or to use `stdin` as input and return the formatted code in `stdout`. The latter is more commonly used in neovim and allows for more flexible solutions where terramate code embedded in a `.md` document could be formatted as well.

**Describe the solution you'd like**
The `stdin` approach allows for the most flexibility. An additional command line flag like `--stdin` could be use to enable this mode or simply `-` as the last argument as common for many command line formatters (terraform fmt included).

**Describe alternatives you've considered**

**Additional context**
Specifically for libraries like [`efmls-configs-nvim`](https://github.com/creativenull/efmls-configs-nvim), the `stdin` approach is preferred.

If I could get some pointers where in the code base to get started with this feature, I'd be happy to give it a go.

**Comment by vtimd** [comment]
Thank you for raising this issue. I just wanted to acknowledge for you. That engineering has seen this. The conversation internally has already started. We will work on this and get back to you soon. Let us know if you have any questions, or have any more details or clarification you would like to add.

**Comment by mariux** [comment]
This feature is planned for development and will be available in one of the next releases.
