### ISSUE TITLE
[FEATURE] Partial evaluation for globals question

### ISSUE THREAD

**Issue by silazare** [terramate-io/terramate#1253]
**Is your feature request related to a problem? Please describe.**
Is there any way to use partial evaluation or skip evaluation for datasources usage in globals ?

For example, I am using one unified module between different stacks and want to use as module input different values per stack which is also could be taken from remote datasources.

Code example:
module `config.tm.hcl`:
```
 generate_hcl "main.tf" {
  content {
    module "eks" {
      source = "../../modules/eks"
      ...
      cluster_endpoint_cidrs         = global.cluster_endpoint_cidrs
      ...
}
```

stack-a `config.tm.hcl`
```
import {
  source = "../../modules/eks/config.tm.hcl"
}

globals {
  cluster_endpoint_cidrs = [
    "0.0.0.0/0",
  ]
}
```

stack-b `config.tm.hcl`
```
import {
  source = "../../modules/eks/config.tm.hcl"
}

globals {
  cluster_endpoint_cidrs = data.terraform_remote_state.vpc.outputs.vpn_ip
}
```

Error example:
```
Code generation report

Failures:

- /eks-staging
	error: /eks-staging/config.tm.hcl:21,31-84: loading globals: global eval: unknown variable namespace: data
```
Now as per document partial evaluation is working only with `generate_hcl`. 

**Describe the solution you'd like**
Allow to skip the evaluation during usage/merging globals with datasources.

**Describe alternatives you've considered**
Just use datasource only during `generate_hcl` code generation or define exact values in globals:
module `config.tm.hcl`:
```
 generate_hcl "main.tf" {
  content {
    module "eks" {
      source = "../../modules/eks"
      ...
      cluster_endpoint_cidrs         = data.terraform_remote_state.vpc.outputs.vpn_ip
      ...
}
```

**Comment by i4ki** [comment]
Hi @silazare 

The `globals` block do not support partial evaluation (atm).

What you can do is support two ways of setting the endpoints cidrs, and use `tm_hcl_expression()` when an expression is needed.

Example:

```hcl
# ../../modules/eks/config.tm.hcl"

generate_hcl "main.tf" {
  content {
    module "eks" {
      source = "../../modules/eks"
      ...
      cluster_endpoint_cidrs         = tm_try(
          global.cluster_endpoint_cidrs,
          tm_hcl_expression(global.cluster_endpoint_cidrs_expr),
      )
      ...
}
```

and then in stack-a you define:

```hcl
import {
  source = "../../modules/eks/config.tm.hcl"
}

globals {
  cluster_endpoint_cidrs = [
    "0.0.0.0/0",
  ]
}
```

but in stack-b, you define:

```hcl
import {
  source = "../../modules/eks/config.tm.hcl"
}

globals {
  cluster_endpoint_cidrs_expr = "data.terraform_remote_state.vpc.outputs.vpn_ip"
}
```

Does this address your use case?

**Comment by silazare** [comment]
Hello @i4ki 

Yes, this works as expected, thank you very much for the response and suggestion!
