### ISSUE TITLE
[BUG] `terramate eval` tries to decode url like encoded sequences

### ISSUE THREAD

**Issue by g13013** [terramate-io/terramate#1327]
**Describe the bug**
`terramate eval` tries to substitute some url encoded like characters (eg: `%3D` ) in the output and replaces it with (MISSING) if not found

**To Reproduce**

1. Run command `terramate experimental eval --global 'x="E%2BkKhZA%3D"' 'tm_try(global.x, null)'`
2. See `E%!B(MISSING)kKhZA%!D(MISSING)` instead of `E%2BkKhZA%3D`

**Expected behavior**
I expect eval to return the output as is without any modification to the string.

**Log Output**
N/A

**Environment (please complete the following information):**
 - OS `linux`
 - OS Version `ubuntu-23.04`
 - Git Version `2.39.2`
 - Terramate Version `0.4.4-rc1`

**Comment by i4ki** [comment]
Thanks for reporting this @g13013 

Yes, I can reproduce it. It will be fixed ASAP.

**Comment by g13013** [comment]
Nice and quick, thanks @i4ki :)
