### ISSUE TITLE
[BUG] function does not exist on `terramate experimental eval`

### ISSUE THREAD

**Issue by g13013** [terramate-io/terramate#1365]
**Describe the bug**
When running `terramate experimental eval 'tm_fileexists("var/prod.tfvar")'` terramate throws this error
```
eval expression: There is no function named "tm_fileexists"
```

**To Reproduce**
1. run `terramate run -- terramate experimental eval 'tm_fileexists("var/prod.tfvar")'`

**Expected behavior**
All terramate functions supported.

**Log Output**
```
Add logs from Terramate to help debug your problem.
terramate: Executing command "terramate experimental eval tm_fileexists(\"var/prod.tfvar\")"
2024-01-12T15:49:49+01:00 FTL eval "tm_fileexists(\"var/prod.tfvar\")": eval expression: There is no function named "tm_fileexists". file=<cmdline>:1,1-14
Error: one or more commands failed
```

**Environment (please complete the following information):**
 - OS: linux
 - OS Version: Ubuntu 23.04
 - Terramate Version: 0.4.4-rc2

**Comment by i4ki** [comment]
Hi @g13013 

The functions were explicitly disabled for security reasons but this explanation was missing in the docs, sorry. I just improved the docs in #1366 and #1367.

The reasoning is that ideally all FS-related functions must be sandboxed to the project repository and that's not the case at the moment.
We are still not sure if this is the best design or not, so we decided on the safer choice for now.
