### ISSUE TITLE
[FEATURE] Run a script before a stack executes

### ISSUE THREAD

**Issue by vikas027** [terramate-io/terramate#1383]
**Is your feature request related to a problem? Please describe.**

I am working on Azure and have a multi-subscription architecture. If I am sitting on root and I run `terramate run terraform init` command it traverses down to each directory and executes the command.

For example, if my stack structure is like below, I would want to switch the AZ cli context by running the command `az account set --subscription xxxxyyyy`

```bash
envs/dev/terraform_init/stack.tm.hcl
envs/prod/terraform_init/stack.tm.hcl
```

**Describe the solution you'd like**
It would be great to have one of these options
- a script block in the `stack.tm.hcl`

```hcl
script "set_subscription" {
  description = "Set Azure Subscription"
  job {
    commands = [
      ["az", " account", "set", "--subscription", "xxxxyyyy"],
    ]
  }
}
```
- create a `script.tm.hcl` in the root of the directory and import it 
```hcl
import {
  source = "/scripts.tm.hcl"
}
```

**Describe alternatives you've considered**

As of now, I am using these commands to individually run each of the stacks after setting up AZ subscription

```bash
az account set --subscription <dev-subscription-id>
terramate run -C envs/dev terraform init

az account set --subscription <prod-subscription-id>
terramate run -C envs/prod terraform init
```

**Comment by mariux** [comment]
Hi @vikas027 

We have an experimental new feature called Terramate Scripts in the latest version of Terramate CLI.

> [!WARNING] 
> It is experimental and subject to changes, so please use with care. 
> More information can be found here: https://terramate.io/docs/cli/orchestration/scripts

For your described use case, you can do the following in Terramate Scripts

```hcl
script "terraform" "init" {
  description = "Set subscription and run terraform init"

  job {
    commands = [
      ["az", "account", "set", "--subscription", global.az.subscription_id],
      ["terraform init"]
    ]
  }
}
```

you will also need to set the global in the corresponding directories

```hcl
globals "az" {
  subscription_id = "xxxxx"
}
```

This will allow you to run the script defined as `terramate script run terraform init`.

As this is an experimental feature, please be sure to test it before using it. Any feedback is welcome. Please also let us know if this solves your current challenge.

**Comment by vikas027** [comment]
Awesome, let me try it out.

**Comment by vikas027** [comment]
This worked like a charm @mariux .

```hcl
script "terraform" "apply" {
  description = "Set subscription and run terraform apply"

  job {
    commands = [
      ["az", "account", "set", "--subscription", global.az.subscription_id],
      ["terraform", "init"],
      ["terraform", "plan"],
      ["terraform", "apply"]
    ]
  }
}
```

The only thing is that this becomes a little clunky if one has dynamically generated `TF_VAR_*` variables, but I think I can live with this for now.  Feel free to close the issue.

Cheers,
Vikas
