### ISSUE TITLE
[BUG] terramate list --run-order doesn't work

### ISSUE THREAD

**Issue by abtris** [terramate-io/terramate#1388]
**Describe the bug**

**To Reproduce**

1. I want run `terramate list --run-order` described in https://terramate.io/docs/cli/orchestration/
2. Run command 'terramate list --run-order'
3. See error `2024-01-24T13:36:40+01:00 FTL parsing cli args [list --run-order]: unknown flag --run-order`

**Expected behavior**

**Log Output**

```
terramate list
stacks/dev/eastus2
stacks/dev/eastus2/acr
stacks/dev/eastus2/aks

terramate list --run-order
2024-01-24T13:36:40+01:00 FTL parsing cli args [list --run-order]: unknown flag --run-order
```

**Environment (please complete the following information):**
 - OS: MacOS 
 - OS Version 13.6.3
 - Git Version git version 2.43.0
 - Terramate Version 0.4.4

**Comment by soerenmartius** [comment]
Hi @abtris,

Thanks for reporting this!  Let me investigate this with the team and get back to you. In the meantime the old `terramate experimental run-order` command can be used to show the run-order. I'll get back to you shortly.

**Comment by abtris** [comment]
Thanks that works.

**Comment by mariux** [comment]
The feature is merged to `main` and will be available with the next release.

**Comment by soerenmartius** [comment]
Hey @abtris, we juste released https://github.com/terramate-io/terramate/releases/tag/v0.4.5-rc1 now which fixes the issue. A stable release will be issued next week! Again, thanks for reporting this.
