### ISSUE TITLE
[FEATURE] DEB/RPM Package Support for Linux Users

### ISSUE THREAD

**Issue by RocketRene** [terramate-io/terramate#1400]
**Is your feature request related to a problem? Please describe.**

Yes, after installing Terramate via go install, updating it is inconvenient. It doesn't get updated automatically with system updates, unlike other applications.

**Describe the solution you'd like**
Release Terramate in DEB and RPM formats to allow for easier installation and updates through Linux package managers. This can be automated using GoReleaser and distributed via platforms like Fury.io.

**Describe alternatives you've considered**
The current manual installation method, which is less efficient and doesn't integrate with system updates.

**Additional context**
Implementing this requires GoReleaser Pro, costing 15 €/month. This investment seems worthwhile for the enhanced user experience it would provide.

**Comment by i4ki** [comment]
@RocketRene this is fixed now, right? Or would you like to improve it still?

**Comment by soerenmartius** [comment]
Thanks both. We added installation instructions for brew, apt and dnf to the docs at https://terramate.io/docs/cli/installation
