### ISSUE TITLE
[BUG] Documentation: Getting started guide git init default branch problem

### ISSUE THREAD

**Issue by serdardalgic** [terramate-io/terramate#1415]
**Describe the bug**

When I was checking the [Quickstart : getting started document](https://terramate.io/docs/cli/getting-started/), I bumped into this output in my local machine, in the [change detection in action](https://terramate.io/docs/cli/getting-started/#change-detection-in-action) part:

```
serdar@Serdars-Air:~/Development/TerraMate/terramate-quickstart^master ♥
% terramate list -c 
Error: Unable to list stacks
> listing changed stacks error: getting revision "main": failed to exec: /opt/homebrew/bin/git rev-parse main : stderr="fatal: ambiguous argument 'main': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n", stdout="main\n"
```
For the careful eyes, the bug is obvious. The git branch I created was `master` instead of `main`. Although git 2.28 introduced setting the default branch for init command, the default for this default stayed `master`. 

If you haven't bumped into this bug, you probably have the [init.defaultBranch](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch) set in your `.gitconfig` (assuming you're using any git version >2.28.

It might be a good idea to include the default branch in the `git init` command of the tutorial. 

**To Reproduce**
Run
```
git init terramate-quickstart
```
and check if your branch name is `master`. 
When you continue the tutorial, the change-detection in action part gives the above copied error.  

**Expected behavior**
Getting-started Tutorial should work in many different environments. 

**Environment (please complete the following information):**
 - OS: Darwin arm64
 - OS Version Darwin Kernel Version 23.2.0 - MacOs Sonoma 14.2.1 
 - Git Version  2.43.0
 - Terramate Version 0.4.4

**Additional context**
I'd suggest updating [the related document](https://github.com/terramate-io/terramate/blob/main/docs/cli/getting-started/index.md?plain=1#L61-L64) as following:
```
git init -b main terramate-quickstart
```

**Comment by soerenmartius** [comment]
Thanks for reporting this @serdardalgic! We'll make sure to fix this shortly

**Comment by SuperAayush** [comment]
Hey @serdardalgic, I would like to work on this.
