### ISSUE TITLE
[FEATURE] Enhance `generate_hcl` for more dynamic content

### ISSUE THREAD

**Issue by g13013** [terramate-io/terramate#1419]
**Is your feature request related to a problem? Please describe.**
Right now, `for` loops and dynamic evaluation of content is not supported inside the `content` block of `generate_hcl`. `lets` block can be used to prepare the HCL content in the `generate_hcl`, But it doesn't support `tm_hcl_expression` as it's only supported inside the `content` block.

_Use case_:
I want to generate a TF content similar to this

```tf
// output.tf
output "resources" {
    value = {
        module1 = module.module1
        module2 = module.module2
    }
}
```

**Describe the solution you'd like**
It would be interesting to do this by:
  
1. Enabling `for` loops and ternary condition when `let` variables are used
```hcl
generate_hcl "output.tf" {
    lets {
        modules = ["module1", "module2"]
    }
    content {
        output "resources" {
            value = { for mod in let.modules: mod => tm_hcl_expression("module.${mod}") }
        }
    }
}
```
2. Allow  `tm_hcl_expression` inside the `lets` block of `generate_hcl`  
```hcl
generate_hcl "output.tf" {
    lets {
        modules = ["module1", "module2"]
        resources=  { for mod in let.modules: mod => tm_hcl_expression("module.${mod}") }
    }
    content {
        output "resources" {
            value = let.resources
        }
    }
}
```

**Describe alternatives you've considered**
For now the only way I found to generate this content is by using a combination of `generate_file` and `tm_templatefile`! Which is not ideal when dealing with HCL, since we loose the syntax coloration and validation.
I have other use cases that would greatly benefit from this enhancement and make the code much much more readable.

**Comment by mariux** [comment]
Yes, we can confirm this and also can confirm it is already in our backlog to be addressed. The planned solution is to allow partial evaluated values in globals and actually everywhere.

Sadly this is a very complex task with very high effort as this requires a lot of HCL tweaks that are not supported by the default libraries.

In our internal infrastructure we face the same challenge and prioritized this very high accordingly ;)

**Comment by oponomarov-tu** [comment]
@mariux, would the task in your internal backlog address the challenge of `tm_hcl_expression` not working inside `tm_*` functions as well or should I create a separate feature request?

**Comment by cwe1ss** [comment]
I'm running into issues dynamically generating the `configuration_aliases` [for providers in modules](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations). 

E.g., given the following `globals`:

```hcl
globals "providers" "aws" {
  source = "hashicorp/aws"
  version = "~> 5.36.0"
  configuration_aliases = [ "member", "network" ]
}
globals "providers" "random" {
  source = "hashicorp/random"
  version = "~> 3.6.0"
}
```

I want to generate something like this:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.36.0"
      configuration_aliases = [ aws.member, aws.network ]
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6.0"
    }
  }
}
```

But I can't get this to work. 

If I use `tm_dynamic "required_providers"` together with `attributes` (like in your [terramate-quickstart-aws](https://github.com/terramate-io/terramate-quickstart-aws/blob/754fce3acee0071f1ac74c59a9f731ed6e1cc954/imports/mixins/terraform.tm.hcl#L40-L42) then I would have to use `tm_hcl_expression` in a `lets`-block (to convert the strings into non-string hcl statements), but that's not supported in `lets`.

If I instead try to somehow use the `content`-block, where `tm_hcl_expression` is supported, I'm having the issue that I can't loop over the providers, because doing `tm_dynamic "required_providers"` with `for_each` and `labels = [provider.key]` results in `required_providers "aws"`, which is invalid syntax. `aws` has to be a non-escaped key within the `required_providers`-block. 😢

**Comment by cwe1ss** [comment]
I played around with this a little more and got quite close to what I would need by (mis)using `tm_merge` to loop within a `content`-block. However, any call to `tm_hcl_expression()` within that context throws a go panic. 

```hcl
globals "providers" {
  aws = {
    source = "hashicorp/aws"
    configuration_aliases = [
      "aws.member",
      "aws.network",
    ]
  }
  random = {
    source = "hashicorp/random"
    configuration_aliases = [
    ]
  }
}

generate_hcl "terraform.tf" {
  content {
    terraform {
      required_version = ">=1.6.0"
      tm_dynamic "required_providers" {
        attributes = tm_merge({
          for k, v in global.providers : k => {
            source = v.source

            # Generated result:
            #   configuration_aliases = ["aws.member", "aws.network", ]
            # Terraform error:
            #   Invalid expression. A single static variable is required
            #
            # configuration_aliases = v.configuration_aliases

            # "terramate generate" fails with:
            #   panic: cannot produce tokens for customdecode.ExpressionVal(...)
            configuration_aliases = tm_hcl_expression("foo")
          }
        })
      }
    }
  }
}
```

![image](https://github.com/terramate-io/terramate/assets/4581460/54430229-1f28-4d48-976e-603940517816)
(Sorry, I can't copy the log from where I wrote it)

**Comment by mariux** [comment]
Hi @cwe1ss 

As a work-around you can use the following code that will generate your desired configuration, it assumes that the `configuration_aliases` are always to be converted to HCL and always provided in the global as a string representing HCL:

```hcl
globals "providers" {
  aws = {
    source = "hashicorp/aws"
    configuration_aliases = "[aws.member, aws.network]"
  }
  random = {
    source = "hashicorp/random"
    configuration_aliases = "[]"
  }
}

generate_hcl "terraform.tf" {
  content {
    terraform {
      required_version = ">=1.6.0"
      tm_dynamic "required_providers" {
        for_each = global.providers

        attributes = {
          (required_providers.key) = {
            source = required_providers.value.source
            configuration_aliases = tm_hcl_expression(required_providers.value.configuration_aliases)
          }
        }
      }
    }
  }
}
```

Please let us know about the success of this work-around.

**Comment by mariux** [comment]
@oponomarov-tu @cwe1ss 

We are still working on native support for HCL expressions inside of globals but sadly can not give an ETA yet. But we added the `planned` label as we are planning to have it resolved in the near future.

**Comment by cwe1ss** [comment]
@mariux thank you for your quick response and the suggestion. unfortunately, this also doesn't work because it seems like `required_providers` may only declared once in terraform - I get this error on `terraform validate`:
```
Error: Duplicate required providers configuration
A module may have only one required providers configuration.
```

```hcl
-- terraform.tf (created)--
// TERRAMATE: GENERATED AUTOMATICALLY DO NOT EDIT

terraform {
  required_version = ">=1.6.0"
  required_providers {
    aws = {
      source = "hashicorp/aws"
      configuration_aliases = [
        aws.member,
        aws.network,
      ]
    }
  }
  required_providers {
    random = {
      source = "hashicorp/random"
      configuration_aliases = [
      ]
    }
  }
}
```

**Comment by mariux** [comment]
@g13013 We just also noticed we never sent a work-around for the original use-case. Sorry for missing out here. 

The original use-case can be generated using a similar trick of templating the desired HCL and converting it to HCL upon code generation

```hcl
generate_hcl "output.tf" {
  lets {
    modules   = ["module1", "module2"]
    resources = "{%{for m in let.modules }${m} = module.${m},%{endfor}}"
  }

  content {
    output "resources" {
      value = tm_hcl_expression(let.resources)
    }
  }
}
```

**Comment by mariux** [comment]
@cwe1ss damn terraform ;) 

okay the work-around to unblock you would be to use `generate_file` with string templating like in:

```hcl
globals "providers" {
  aws = {
    source                = "hashicorp/aws"
    configuration_aliases = "[aws.member, aws.network]"
  }
  random = {
    source                = "hashicorp/random"
    configuration_aliases = "[]"
  }
}

generate_file "terraform.tf" {
  content = <<EOF
terraform {
  required_version = ">= 1.6.0"
  required_providers {
  %{~for p, v in global.providers~}
    ${p} = {
      source                = "${v.source}"
      configuration_aliases = ${v.configuration_aliases}
    }
  %{~endfor~}
  }
}
  EOF
}
```

we will provide a better solution at some point ;)
