### ISSUE TITLE
[BUG] README link for CNCF leads to a 404 - Page Not Found

### ISSUE THREAD

**Issue by garyboyes** [terramate-io/terramate#1427]
**Describe the bug**
- When clicking through the links in the README file, the link for the CNCF page appears to have moved since it was last updated, leading to a 404

**To Reproduce**
- Viewing the README, scroll to the bottom and click on the CNCF hyperlink

**Expected behavior**
- Would expect to be linked to the Terramate page on the CNCF site

**Log Output**
![image](https://github.com/terramate-io/terramate/assets/78487184/e1b0335e-5f05-4241-911e-af5b26af71d1)

**Environment (please complete the following information):**
- N/A - Confirmed in Chrome and Safari

**Additional context**
- None

**Comment by garyboyes** [comment]
No probs!

**Comment by soerenmartius** [comment]
I opened a PR to fix this in https://github.com/terramate-io/terramate/pull/1428
