### ISSUE TITLE
[BUG] Escape sequences being interpreted in heredocs

### ISSUE THREAD

**Issue by matthewdean118118** [terramate-io/terramate#1449]
**Describe the bug**
Escape sequences are interpreted in heredocs during code generation (eg \n is replaced with a newline)

**To Reproduce**
The following Terramate code
```
generate_hcl "generated_test.tf" {
  content {
    resource "local_file" "foo" {
      filename = "./output_tm.txt"
      content = <<DOC
          Line 1
          Line 2. I want the following \ and n to be in the file: \n
          Line 3
      DOC
    }
  }
}
```
generates Terraform code:
```
// TERRAMATE: GENERATED AUTOMATICALLY DO NOT EDIT

resource "local_file" "foo" {
  content = <<-EOT
          Line 1
          Line 2. I want the following \ and n to be in the file: 

          Line 3
EOT

  filename = "./output_tm.txt"
}
```

So, after apply, the contents of output_tm.txt are:
```
Line 1
Line 2. I want the following \ and n to be in the file:

Line 3
```

Instead of my desired:
```
Line 1
Line 2. I want the following \ and n to be in the file: \n
Line 3

```

Also escaping the backslash (eg using \\\n) doesn't help

**Expected behavior**
The literal \n to be preserved, as Terraform does. https://developer.hashicorp.com/terraform/language/expressions/strings#escape-sequences-1

**Log Output**

**Environment (please complete the following information):**
 - OS: Linux
 - OS Version: Ubuntu 23.10
 - Git Version: 2.40.1
 - Terramate Version: 0.4.5

**Additional context**
Terramate is awesome - thanks for making it!

**Comment by i4ki** [comment]
This fix was released on [v0.5.0](https://github.com/terramate-io/terramate/releases/tag/v0.5.0).
