### ISSUE TITLE
terramate list --changed fails on diverging branch name

### ISSUE THREAD

**Issue by juweins** [terramate-io/terramate#1514]
**Describe the bug**
When following the tutorial, the command terraform list --changed fails with the following error:

Error: Unable to list stacks
> listing changed stacks error: getting revision "main": failed to exec: /usr/bin/git rev-parse main : stderr="fatal: ambiguous argument 'main': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n", stdout="main\n"

<img width="724" alt="image" src="https://github.com/terramate-io/terramate/assets/26652109/5ef5557a-68f3-40f1-ba3a-e77b43b6084a">

This is due to the fact that my .gitconfig uses master instead of main as a trunk/default branch.

**To Reproduce**

1. change to alternative git default branch 'git config --global init.defaultBranch **master**'
2. Create two stacks tracked with git (as per quickstart)
3. Run command 'terramate list --changed'
4. See error above

**Expected behavior**
The command should take different naming into consideration.

**Log Output**
none needed. Clean installation

**Environment (please complete the following information):**
 - OS: WSL
 - OS Version Ubuntu 22.04.3 LTS
 - Git Version 2.34.1
 - Terramate Version 0.4.6

**Comment by i4ki** [comment]
Hi @juweins 

Terramate works with any branch name but the tutorial expects `main`. This has been reported before (https://github.com/terramate-io/terramate/issues/1415) and the quickstart guide is being fixed here: https://github.com/terramate-io/terramate/pull/1495
Thanks for the feedback, anyway :)

If you would like to use `master`, then add the configuration below at the root of your repository:

```hcl
# terramate.tm.hcl

terramate {
  config {
    git {
      default_branch = "master"
    }
  }
}
```

I'm going to close this one, but feel free to reopen if you think some improvements are still needed.

Thank you.
