### ISSUE TITLE
[BUG] terramate fmt --detailed-exit-code does not change files

### ISSUE THREAD

**Issue by cwe1ss** [terramate-io/terramate#1649]
**Describe the bug**
Calling `terramate fmt --detailed-exit-code` does return status code `2` when a terramate file is incorrectly formatted, but it does not actually format the file.

**To Reproduce**

1. Change a terramate file in a way that it's incorrectly formatted (e.g. by including spaces)
2. Run command `terramate fmt --detailed-exit-code`
3. The exit code will be `2`, but the file will not have changed

**Expected behavior**
`terramate fmt --detailed-exit-code` should format the files so that it's consistent with `terramate generate --detailed-exit-code`.

**Environment (please complete the following information):**
 - OS: Windows
 - OS Version: 11
 - Git Version: 2.44.0.windows.1
 - Terramate Version: 0.6.3

**Additional context**
Originally commented in https://github.com/terramate-io/terramate/issues/1312#issuecomment-1951797427

**Comment by mariux** [comment]
Thanks for catching this little regression here. We are going to fix the issue and send out a release asap.

**Comment by i4ki** [comment]
Hi @cwe1ss 

Sorry, I also missed the comment in the other issue.

We released [`v0.6.4`](https://github.com/terramate-io/terramate/releases/tag/v0.6.4) with the fix! Thanks for reporting it.
