### ISSUE TITLE
[BUG] Error: repository has untracked files

### ISSUE THREAD

**Issue by az-z** [terramate-io/terramate#1672]
**Describe the bug**
if the repo / current directory has uncommited files "terramate generate" fails with "Error: repository has untracked files"

**To Reproduce**
git clone <your repo>
<add a file>
terramate generate

// above assumes the repo is configured for TM 

**Expected behavior**
the previous version of TM did not have this behavior.
In ideal world running the tm generate only on committed changes makes sense. At the same time, it gets in the way when i want to "sanity check" the configuration. This forces me to check in all, even temp files that i not necessary going to have in the repo in 5 minutes.
Very frustrating experience. 

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - OS Version [e.g. Ubuntu 20.04]
 - Git Version [e.g. 2.35.1] (git --version)
 - Terramate Version [e.g. 0.1.0] (terramate --version)

**Additional context**

**Comment by i4ki** [comment]
Hi @az-z 
What's your Terramate version?

**Comment by i4ki** [comment]
```
 $ terramate generate
Nothing to do, generated code is up to date
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   terramate.tm.hcl

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	terramate.prof

no changes added to commit (use "git add" and/or "git commit -a")
$ terramate generate
Nothing to do, generated code is up to date
```

Generate does not check for untracked/uncommitted files.
Please provide more details so we can reproduce this.

**Comment by az-z** [comment]
It is 0.6.3 on fedora 39

**Comment by az-z** [comment]
Give me a few hours, pleae.

**Comment by az-z** [comment]
here we go :
```
az@ip-10-0-2-15: D9/DEV$ git status
On branch feature/WWWPRIV-229-implement-ssm-parameter-stor
Your branch is up to date with 'origin/feature/WWWPRIV-229-implement-ssm-parameter-stor'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   globals.tm

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    ../../../../1
	modified:   globals.tm
	modified:   ../../config/Security/security_groups.tf
	modified:   ../../../../terramate.tm
	deleted:    ../../../../terramate.tm.hcl

az@ip-10-0-2-15: D9/DEV$ alias -p | grep tmi
alias tmi='terramate generate  && terramate --log-level=info  -C ./ run   -- terraform init'
az@ip-10-0-2-15: D9/DEV$ ls -la
total 13
drwxrwx--- 1 root vboxsf    0 Apr 25 14:35 .
drwxrwx--- 1 root vboxsf 4096 Dec 31  1969 ..
drwxrwx--- 1 root vboxsf 4096 Apr 25 14:35 cicd
drwxrwx--- 1 root vboxsf 4096 Apr 25 13:05 comp
-rwxrwx--- 1 root vboxsf  687 Dec 31  1969 globals.tm
az@ip-10-0-2-15:  D9/DEV$ cat ../../../../terramate.tm 
# file: terramate.tm.hcl
terramate {
  config {
  git {
    default_branch = "master"
#    check_untracked = false
#    check_uncommitted = false
    }
  }
}
az@ip-10-0-2-15:D9/DEV$ tmi
Nothing to do, generated code is up to date
Error: repository has uncommitted files
```

**Comment by az-z** [comment]
now, if i un-comment both "check" variables and run ```terramate init``` the command executes as expected with the ```terraform init`` execution:

```
D9/DEV$ tmi
Nothing to do, generated code is up to date
terramate: Entering stack in /Clients/SOPRO/D9/DEV/cicd
terramate: Executing command "terraform init"

Initializing Terraform Cloud...
.....
```

and TF apply works as expected....

**Comment by az-z** [comment]
Oh, I see. Yes, this should work. I'll update the project config with the
new section.
Thank you so much for your help!

**Comment by az-z** [comment]
Please close as "not a bug" and resolved

**Comment by az-z** [comment]
@i4ki ,
 very sorry to update the closed ticket.
I think you might want to update the example here https://terramate.io/docs/cli/orchestration/safeguards#example-of-a-project-config-disabling-all-checks
that and this https://terramate.io/docs/cli/configuration/#terramate-config-git-block-schema can be confusing.
