### ISSUE TITLE
[BUG] runtime removes all characters from env value after `=`

### ISSUE THREAD

**Issue by 1mr** [terramate-io/terramate#1710]
**Describe the bug**
If the env value contains `=`, then all characters after `=` will be removed in `terramate.config.run.env`

**To Reproduce**

1. Source data
```
env | grep KEY
KEY1=adasd=
KEY2=adasd=adasd
KEY3=adasd==
KEY4=a=adasd

```
```
terramate {
  config {
    run {
      env {
        KEY1 = env.KEY1
        KEY2 = env.KEY2
        KEY3 = env.KEY3
        KEY4 = env.KEY4
      }
    }
  }
}
```

2. Run command `tm debug show runtime-env`
3. See modified values
```
stack "/terraform/test":
	KEY1=adasd
	KEY2=adasd
	KEY3=adasd
	KEY4=a
	TF_PLUGIN_CACHE_DIR=~/.terraform.d/plugin-cache
```

**Expected behavior**
Do not change env values and handle the `=` character in env values correctly.

```
# tm debug show runtime-env
stack "/terraform/test":
	KEY1=adasd=
	KEY2=adasd=
	KEY3=adasd=adasd
	KEY4=a=adasd
	TF_PLUGIN_CACHE_DIR=~/.terraform.d/plugin-cache
```

**Log Output**
-

**Environment (please complete the following information):**
 - OS: macOS
 - OS Version [14.4.1]
 - Git Version [2.39.3] (git --version)
 - Terramate Version [0.8.3] (terramate --version)

**Comment by i4ki** [comment]
Hi @1mr 

Thanks for reporting this. It's fixed here https://github.com/terramate-io/terramate/pull/1711
and will be included in the next release.
I will let you know when released.
