### ISSUE TITLE
[BUG] Version constraint check is not working properly

### ISSUE THREAD

**Issue by athak** [terramate-io/terramate#1726]
**Describe the bug**
The version constraint check is not working properly. I have the following in the `terramate.tm.hcl` file:
```hcl
required_version = ">= 0.8.0"
```
And the latest version installed via APT, currently `0.9.0-rc1`. Running `terramate generate` or any other command errors with the following output:
```
Error: version check failed
version check error: version constraint ">= 0.8.0" not satisfied by terramate version "0.9.0-rc1"
```
I suspect it's not parsing the `-rc1` suffix correctly.

**To Reproduce**

1. Set a version constraint in the `terramate`, e.g. `required_version = ">= 0.8.0"`
2. Install the latest pre-release `terramate` version
3. Run a `terramate` command

**Expected behavior**
It should parse the version correctly and consider `0.9.0-rc1` a higher version than `0.8.0`.

**Log Output**
See above.

**Environment (please complete the following information):**
 - OS: all
 - Terramate Version: 0.9.0-rc1

**Comment by i4ki** [comment]
Hi @athak 

Did you enable the `terramate.required_version_allow_prereleases` flag?
By default the constraint check ignores prereleases.
Check docs [here](https://terramate.io/docs/cli/projects/configuration#the-terramate-required-version-attribute).
```
terramate {
  required_version = ">= 0.8.0"
  required_version_allow_prereleases = true
}
```

let me know if this fixes your problem.

**Comment by athak** [comment]
Hi @i4ki

My bad, I missed that flag in the docs!
