### ISSUE TITLE
[BUG] reference from tm_hcl_expression in tm_format

### ISSUE THREAD

**Issue by julienfig** [terramate-io/terramate#1811]
**Describe the bug**
Hello,

we try to add somes tags on folders dynamically.
We can't find a way to manage dynamic hcl expressions 

**To Reproduce**

    tm_dynamic "data" {
      for_each = global.folders.names
      iterator = value
      labels   = ["google_active_folder", value.value]
      content {
        display_name = value.value
        parent       = "folders/XXXXXXXX"
      }
    }

    tm_dynamic "resource" {
      for_each = global.folders.names
      iterator = folder
      labels   = ["google_tags_tag_binding", folder.value]
      content {
        parent = tm_format("//cloudresourcemanager.googleapis.com/%s",tm_hcl_expression("data.google_active_folder.${value.value}.name"))
        tag_value = tm_hcl_expression("google_tags_tag_value.${folder.value}.id")
      }
   
    
global.folders.names is a list like ["gerard","roger","force4"]
 tag_value = tm_hcl_expression("google_tags_tag_value.${folder.value}.id"). this part is ok
--> the "terramate generate" command gives back this errror

eval expression: Call to function "tm_format" failed: unsupported value for "%!s(MISSING)" at 38: string required.
       
**Expected behavior**
the output of tm_hcl_expression("data.google_active_folder.${value.value}.name") is "folders/XXXX" and we would like to concatenate it with the string "//cloudresourcemanager.googleapis.com/" as prefix. 

so we try with tm_format but it gives the error

will appreciate any help :) thanks 

**Environment:**
 - OS: MacOS
 - OS Version somona 14.5
 - Git Version 2.39.3
 - Terramate Version   0.9.1

**Additional context**

**Comment by i4ki** [comment]
Hi @julienfig 

The `tm_hcl_expression()` returns a raw HCL expression then it cannot be nested into other expressions, it needs to wrap all others.

Can you run the code below and confirm if this is the output you want?

```
globals "folders" {
  names = ["gerard","roger","force4"]
}

generate_hcl "test.tf" {
  content {
    tm_dynamic "data" {
      for_each = global.folders.names
      iterator = value
      labels   = ["google_active_folder", value.value]
      content {
        display_name = value.value
        parent       = "folders/XXXXXXXX"
      }
    }

    tm_dynamic "resource" {
      for_each = global.folders.names
      iterator = folder
      labels   = ["google_tags_tag_binding", folder.value]
      content {
        parent    = tm_hcl_expression("\"//cloudresourcemanager.googleapis.com/$${data.google_active_folder.${folder.value}.name}\"")
        tag_value = tm_hcl_expression("google_tags_tag_value.${folder.value}.id")
      }
    }
  }
}
```

It looks a bit ugly but if you confirm it's the right output, we will check if we can improve the expression handling to make this easier.

**Comment by julienfig** [comment]
Hi i4ki

First, i would like to thank you.

it's working. we are happy to know that tm_hcl_expression() needs to wrap all the expression we need to manipulate.
ilt will help in the following development.

Julien
