### ISSUE TITLE
[FEATURE] Provide way for advanced dynamic code generation 

### ISSUE THREAD

**Issue by maulik13** [terramate-io/terramate#1852]
> [!Note]
> After some thoughts, I think I can summarize this feature as dynamically generating attribute assignments. 

**Is your feature request related to a problem? Please describe.**
We create Terraform modules separately for different parts of our infrastructure. Then we create a corresponding hcl file to use this module from a GitHub repo. The target "Stack" will refer this hcl file to generate the code. In this hcl file we mostly add the required parameters for the module. So the hcl file looks like this:

```hcl
generate_hcl "_terramate_auto_env_postgres.tf" {
  content {
    module "postgres" {
      source               = "git@github.com:xxxx"
      environment          = global.environment_type
      location             = global.location
      name_prefix          = global.resource_name_prefix
      postgres_rg_name     = "${global.resource_name_prefix}-db-rg"
      size                 = global.database.postgres_sku_size
      tier                 = global.database.postgres_sku_tier
      storage_mb           = global.database.postgres_storage_mb
      postgres_version     = global.database.postgres_version
      standard_tags        = global.standard_tags
      zone                 = global.database.postgres_zone
    }
  }
}
``` 

However, the Terraform module supports more optional parameters which we would like to override as well. So in the example above we have `zone` variable that is actually optional, but we want some Stacks to be able to override it. 

What we have to do in this case is to define `zone` in the common global block with a default value (which is the same one as defined in the Terraform module). Hence we have to duplicate this. When we have a Terraform module with 10-20 optional variables we want to override we have to do this same exercise which will end up duplicating default values between our common global config block and individual Terraform modules. 

**Describe the solution you'd like**
Ideally, we would like to generate some of these parameter dynamically only if the global object contains a value for it in a given Stack. I am not sure how it would look like. 

```hcl
generate_hcl "_terramate_auto_env_postgres.tf" {
  content {
    module "postgres" {
      # ...
      standard_tags = global.standard_tags
      tm_if_global_exists {
        zone           = global.database.postgres_zone
      }
    }
  }
}
```

This should then generate final TF code
```hcl
module "postgres" {
  source = "xxxx"
  #...
  standard_tags = {
    environment = "prod"
  }
  zone = "1"
}
``` 

This will be a great feature to be able to add more optional parameters without redeclaring the same variable in our common global object with the same default value as the Terraform modules. 

**Describe alternatives you've considered**
I tried looking at `tm_templatefile`, but have not managed to figure out how that can solve my issue since we need to generate this content in an existing generate_hcl block.

**Comment by i4ki** [comment]
Hi @maulik13 

Are you familiar with the hierarchical nature of the Terramate globals? Is it correct to say that need the inverse of it, where parent (or common) declaration takes precedence over child ones?

You can have both approaches with Terramate, but using the filesystem hierarchy is usually what users want and is easier.

## Child overriding parent
The globals declared in child directories override the ones declared in parent directories. So if you have:
```
# /common.tm
globals "env" {
  zone = "default_zone"
}
```
declared somewhere in a common directory, then all stacks will see this.

You can choose to override `global.env.zone` just in some stacks, then you do:
```
# /stacks/vpc/config.tm
globals "env" {
  zone = "stack_specific_zone"
}
```

## Parent overriding child

If you need the other way around, with each stack defining explicitly everything and then allowing overrides at parent levels (very unusual setup), then you need to rely a lot in `tm_try` (eg.: `tm_try(global.overrides.zone, global.zone)`).

Example: Target stack defines all values needed by the generate block but gives preferences for overrides.
```
# /stacks/stack-1
globals {
  environment = tm_try(global.overrides.environment, "my env")
  location    = tm_try(global.overrides.location, "my location")
  // ... all other values ...
  zone        = tm_try(global.overrides.database.postgres_zone, "my zone")
}
```

Then if later on you need to override one specific global value in some stacks, you can set this somewhere only visible to that subset of stacks:

```
globals "overrides" {
  zone = "other zone"
}
```

If the second case is what you need, would that solve your problem?
If not, then please answer my question and elaborate a bit further in the use case.

**Comment by maulik13** [comment]
@i4ki thank you for your detailed reply. I think you misunderstood the problem I tried describing. We already utilize the hierachy of stacks today. What we want to override are not globals and are not in the same folder structure.  

There are two parts to address as part of this problem we are looking to solve:

1. We want to specify environment specific overrides of default values from Terraform module variables.
2. How do we do the above without redeclaring the same variable (defined in a separate git repo as a TF module) as globals in our environment setup. 

So in my example with postgres above, we have a separate GitHub repo that holds our Terraform module for postgres and it has a variable with a default value like this:

```Terraform
variable "zone" {
  description = "Specify availability-zone for PostgreSQL Flexible main Server."
  type        = string
  default     = "1"
}
```

Then we have our environments repository which holds our stack structure and utilizes all our Terraform modules (all in separate repo). In most environments we will use zone 1, however we have a few environments where we want to choose something else. 

The way we have to do today is to declare a global `global.database.postgres_zone` and set its value to match the default value from the TF module. Then our stack template will use this global variable (see code snippet #1  in my post). Then a child environment who wants to use different zone will specify the global value and it works. But the problem is duplicating the default value and redeclaring the same variable from TF module in to our stack structure gets unmaintanable considering we have 50+ optional variables with defaults spanning multiple Terraform modules. 

I hope this makes sense :D

**Comment by maulik13** [comment]
@i4ki So basically I am looking for dynamically generating attribute assignments. Just like we have `tm_dynamic` for blocks.

**Comment by maulik13** [comment]
This looks like almost what we are looking for. It definitely solves the major issue of not needing to redefine the default values. I don't know how I missed this feature in the documentation 😅. 

Really appreciate your help!
