### ISSUE TITLE
[FEATURE] Support specifying data types for "Input" block for output sharing

### ISSUE THREAD

**Issue by maulik13** [terramate-io/terramate#1861]
**Is your feature request related to a problem? Please describe.**
We followed the instructions from the documentation and created sharing_backend, output and input. After generting the code we see that input blocks creates a variable which has type "string". Our output parameter type however is a map. We did not find any way to override or remove this "string" type and hence we could not use the output sharing feature.  

**Describe the solution you'd like**
Ability to specify data type in the Input block or just remove the type? 

**Describe alternatives you've considered**
No alternatives that we could find

**Comment by mariux** [comment]
Hi @maulik13 , thank you for the feedback. A fix will be included in the upcoming release.

**Comment by maulik13** [comment]
@mariux appreicate the quick response and looking forward to the upcoming release :) Terramate is looking better and better with each release.

**Comment by i4ki** [comment]
Hey @maulik13 

We fixed this in the [`v0.10.5`](https://github.com/terramate-io/terramate/releases/tag/v0.10.5) release. Can you check if it solves your problem?

Please give us feedback if something does not work as expected or what you would like to see next in this feature, so we can plan better the next iterations.

Thank you for the help!
