### ISSUE TITLE
[FEATURE] Support --tags option for `terramate create --all-terragrunt`

### ISSUE THREAD

**Issue by LittleWat** [terramate-io/terramate#1966]
**Is your feature request related to a problem? Please describe.**

I've run `terramate create --all-terragrunt --tags dev` but the resulting `stack.tm.hcl` file did not contain the tag field.

**Describe the solution you'd like**

 `terramate create --all-terragrunt --tags dev`  should generate `stack.tm.hcl` that contains the tag field.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ltshb** [comment]
It would also be great to be able to set tags not just upon creation but also add tags based on path filter or to all stack down below the current folder. This would be of a great help to be able to manage stack of big projects. 
I just started to use terramate for our terraform repository that contains over 300 root modules. Currently I don't use tags as I did not wanted to go over the 300 modules to set them.

**Comment by i4ki** [comment]
> It would also be great to be able to set tags not just upon creation but also add tags based on path filter or to all stack down below the current folder. This would be of a great help to be able to manage stack of big projects.

yes, this in the roadmap!

**Comment by adrianvillanueva997** [comment]
> Hi @LittleWat
> 
> yes, it's actually a bug. Thanks for reporting this! It will be fixed as soon as possible.

Also it would be nice to be able to edit already existing stacks, once a stack it is created you cannot apply a tag or watchfile or anything. It seems that all the options are locked to be only used on creation time, i dont know if this makes sense.
