### ISSUE TITLE
[FEATURE] Detect the Terragurnt dependency when using `file` syntax

### ISSUE THREAD

**Issue by LittleWat** [terramate-io/terramate#1967]
**Is your feature request related to a problem? Please describe.**

I have the following `terragrunt.hcl` file.

```hcl
include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "git::my_tf_module"
}

locals {
  my_vars = yamldecode(file("../../../_envcommon/my_var.yaml"))
}

inputs = {
  "vars" : local.my_vars,
}

```

I have updated `../../../_envcommon/my_var.yaml` but Terramate could not detect the change in this module

Based on https://terramate.io/docs/cli/change-detection/integrations/terragrunt , `file` syntax seems not to be supported, unfortunately...?

**Describe the solution you'd like**

Support this `file` syntax

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by i4ki** [comment]
Hi @LittleWat 

I think it makes sense to support it as well.
We are going to have a few Terragrunt fixes and improvements in the next release and we will try to include this one.

Thanks for the report!
