### ISSUE TITLE
[BUG] Stacks are not generated from existing Terragrunt modules

### ISSUE THREAD

**Issue by Neonox31** [terramate-io/terramate#1969]
**Describe the bug**

First, thanks a lot for your work on this tool 👍

I tried to generated stacks from existing Terragrunt modules with appropriate `create` command but nothing is generated.
The command has a succcess exit code with no output.

**To Reproduce**

I created a bare minimum GIT repository with 3 distinct Terragrunt modules :
```
 .
├──  bar
│   ├── 󱁢 main.tf
│   └──  terragrunt.hcl
├──  baz
│   ├── 󱁢 main.tf
│   └──  terragrunt.hcl
└──  foo
    ├── 󱁢 main.tf
    └──  terragrunt.hcl
```
Each module contains an empty `terragrunt.hcl` file and a `main.tf` Terraform file with only one  variable :
```hcl
# bar/main.tf

variable "folder" {
  type = string
  default = "bar"
}
```
When I run `terramate create --all-terragrunt`, the command output is empty an no stack files are created inside modules.

**Expected behavior**

After running `terramate create --all-terragrunt` command, find in each terragrunt module a `stack.tm.hcl` stack file :

```
Created stack /foo
Created stack /bar
Created stack /baz
```

**Log Output**

```
❯ terramate create --all-terragrunt --log-level="trace"
2024-11-25T14:30:36+01:00 DBG Get git version. action=Version() workingDir=/tmp/terramate
2024-11-25T14:30:36+01:00 DBG Set defaults. action=setDefaults() workingDir=/tmp/terramate
2024-11-25T14:30:36+01:00 DBG project root config has no required_version, skipping version check action=cli.checkVersion() root=/tmp/terramate
2024-11-25T14:30:36+01:00 DBG Handle command. action=run() cmd=create workingDir=/tmp/terramate
2024-11-25T14:30:36+01:00 TRC found configuration action=tg.ScanModules cfg-file=/tmp/terramate/bar/terragrunt.hcl
2024-11-25T14:30:36+01:00 TRC found configuration action=tg.ScanModules cfg-file=/tmp/terramate/baz/terragrunt.hcl
2024-11-25T14:30:36+01:00 TRC found configuration action=tg.ScanModules cfg-file=/tmp/terramate/foo/terragrunt.hcl
```

**Environment (please complete the following information):**

 - OS: Linux
 - OS Version EndeavoursOS
 - Git Version 2.47.0
 - Terramate Version 0.11.2
 - Terragrunt Version 0.68.4

**Comment by i4ki** [comment]
Hi @Neonox31 

An empty `terragrunt.hcl` file is not enough. The `terramate create --all-terragrunt` is supposed to be used to onboard existing Terragrunt projects, so you need the actual `terraform` block defined and everything.

So if you are just creating a new Terragrunt project from scratch, this `create --all-terragrunt` is not useful.

**Comment by i4ki** [comment]
Hey @Neonox31 

I'm closing this issue but if you think we should reconsider please feel free to reopen.
Thank you

**Comment by Neonox31** [comment]
Hello @i4ki 

First thanks a lot for your answer and sorry for my late answer.

I tried to expose a simple case here but I got an existing repo with multiple Terragrunt modules at work and I cannot generate Terramate stacks on it too. FYI, each module contains a `terraform` block and I can run commands on it without problems using Terragrunt command.

What are your throughts on it ?
