### ISSUE TITLE
[BUG] Terramate Swallows Tofu Errors When Getting Stack Output

### ISSUE THREAD

**Issue by ImIOImI** [terramate-io/terramate#1975]
**Describe the bug**
When there's an error in the stack with the shared backend, terramate swallows it and reports a generic non-helpful error

**To Reproduce**

1. don't login to AWS
2. run `terramate run --enable-sharing --mock-on-fail -- tofu plan`
3. get the error:
```
terramate: Entering stack in /stacks/aws/dev/eks/core-apps-dev-use1-primary/primary-nodes
Warning: failed to execute `sharing_backend` command: exit status 1
Error: one or more commands failed
```

1.  create a configuration issue like duplicating an output
2. run `terramate run --enable-sharing --mock-on-fail -- tofu plan`
3. get the error:
```
terramate: Entering stack in /stacks/aws/dev/eks/core-apps-dev-use1-primary/primary-nodes
Warning: failed to execute `sharing_backend` command: exit status 1
Error: one or more commands failed
```

**Expected behavior**
I'd expect terramate to bubble up the error logs from the parent stack

**Comment by ImIOImI** [comment]
This made it especially unobvious that I was doing something wrong when figuring out how to share outputs.

**Comment by i4ki** [comment]
Hi @ImIOImI 

Thanks for reporting this. We will include a fix for this in next release.
