### ISSUE TITLE
[BUG][0.11.3] `panic: abspath "/opt/actions-runner/_work/a/b/c" does not start with root "/opt/actions-runner/_work/a/a"`

### ISSUE THREAD

**Issue by LittleWat** [terramate-io/terramate#1979]
**Describe the bug**

After updating the version from 0.11.2 to 0.11.3 , 

```shell
terramate create --all-terragrunt --tags dev
```

command started to fail with the weird error:

```log
panic: abspath "/opt/actions-runner/_work/a/b/c" does not start with root "/opt/actions-runner/_work/a/a"

goroutine 1 [running]:
github.com/terramate-io/terramate/project.PrjAbsPath({0xc000b0c2d0, 0x2d}, {0xc001aaf480, 0x39})
	/home/runner/work/terramate/terramate/project/project.go:126 +0x1b9
github.com/terramate-io/terramate/tg.ScanModules({0xc000b0c2d0, 0x2d}, {{0xc000178aed?, 0x3c?}}, 0x1)
	/home/runner/work/terramate/terramate/tg/tg_module.go:183 +0x2031
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).initTerragrunt(0xc000c9a000)
	/home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:1454 +0x73
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).scanCreate(0xc000c9a000)
	/home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:1447 +0x2c5
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).run(0xc000c9a000)
	/home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:706 +0x4f3
github.com/terramate-io/terramate/cmd/terramate/cli.Exec({0x19ac959, 0x6}, {0xc000142010, 0x4, 0x4}, {0x200a8a0, 0xc00012c040}, {0x200a8c0, 0xc00012c048}, {0x200a8c0, ...})
	/home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:388 +0xfc
main.main()
	/home/runner/work/terramate/terramate/cmd/terramate/main.go:20 +0x89
```

I'm wondering why the root is set to `/opt/actions-runner/_work/a/a` (The directory `a` is repeated)

**Expected behavior**

don't fail.

**Environment (please complete the following information):**

```shell
Operating System
  Distribution: Ubuntu 22.04.5 LTS
  Architecture: x86_64
```

**Comment by i4ki** [comment]
Oh, thanks for reporting this. This was introduced in #1973 (only present in v0.11.3).
This will be fixed ASAP. Please rollback to `v0.11.2` for the time being.

**Comment by i4ki** [comment]
hey @LittleWat 

Are you using `terramate -C <dir> ...` ?

**Comment by i4ki** [comment]
> I'm wondering why the root is set to /opt/actions-runner/_work/a/a (The directory a is repeated)

that's weird.

Can you check in the runner if `/opt/actions-runner/_work/a/a` exists or if it's a symlink?
Maybe run `ls -lha /opt/actions-runner/_work/a /opt/actions-runner/_work/a/a`

**Comment by i4ki** [comment]
sorry for too many questions, but it's not reproducing in my cases.
Are you using *git submodules*?

**Comment by i4ki** [comment]
does it also happen when you run `terramate create --all-terragrunt` locally in your machine?

**Comment by i4ki** [comment]
I managed to reproduce it by using a `dependency` block with a `config_path` pointing to a path outside the Terramate project.
So if you have your Terramate project at `/home/i4k/my-terramate-project`
and inside of it a Terragrunt module with a dependency referencing a `/home/i4k/my-other-terragrunt-project/my-mod`, then running `terramate create --all-terragrunt` panics with this exact same stack trace.

Are you using symlinks to other repositories in the `dependency` blocks?

All paths inside Terramate are relative to the project root, so we cannot generate the `after` and `before` clauses for such configurations...

**Comment by adrianvillanueva997** [comment]
Hi @i4ki, we are working on the same project at the moment as coworkers.

We are not using symlinks in the project. We are just using git sources to define our terragrunt stacks terraform source. 


> Are you using terramate -C <dir> ... ?

No, we use terramate create --all-terragrunt



> does it also happen when you run `terramate create --all-terragrunt` locally in your machine?
Yes, this is the error trace:

```
panic: abspath "/Users/myuser/reponame" does not start with root "/Users/myuser/reponame/"

goroutine 1 [running]:
github.com/terramate-io/terramate/project.PrjAbsPath({0x14000231280, 0x31}, {0x1400090adc0, 0x3d})
        /home/runner/work/terramate/terramate/project/project.go:126 +0x1d8
github.com/terramate-io/terramate/tg.ScanModules({0x14000231280, 0x31}, {{0x140002309b1?, 0x40?}}, 0x1)
        /home/runner/work/terramate/terramate/tg/tg_module.go:183 +0x19ec
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).initTerragrunt(0x14000c10400)
        /home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:1454 +0x60
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).scanCreate(0x14000c10400)
        /home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:1447 +0x2cc
github.com/terramate-io/terramate/cmd/terramate/cli.(*cli).run(0x14000c10400)
        /home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:706 +0x4dc
github.com/terramate-io/terramate/cmd/terramate/cli.Exec({0x103d9a003, 0x6}, {0x1400003a0d0, 0x2, 0x2}, {0x104869fa8, 0x1400007a008}, {0x104869fc8, 0x1400007a010}, {0x104869fc8, ...})
        /home/runner/work/terramate/terramate/cmd/terramate/cli/cli.go:388 +0xb0
main.main()
        /home/runner/work/terramate/terramate/cmd/terramate/main.go:20 +0x94
```

**Comment by LittleWat** [comment]
@i4ki thank you for your investigation!

Here is the sample tree of our repo:

```log
terramate.tm.hcl  [error opening dir]
terragrunt
├── _envcommon
│   └── common.yaml
├── dev
│   └── vpc_flow_s3
│       └── terragrunt.hcl
└── terragrunt.hcl
```

and `terramate create --all-terragrunt` was run at `terragrunt/dev`

How can we fix this issue...?

**Comment by LittleWat** [comment]
Hi, @i4ki thank you for your quick work!

I tried it on my local PC.

I have `/terragrunt/dev/a1/b/c/d/terragrunt.hcl`:

```hcl
dependency "b2" {
  config_path                             = "../../../../a2/b2"
  mock_outputs_allowed_terraform_commands = ["validate", "plan", "refresh"]
  mock_outputs_merge_strategy_with_state  = "shallow"
  mock_outputs                            = {
    metastore_id = "fake_metastore_id"
  }
}
```

It could successfully finish.

```shell
$ cd terragrunt/dev
$ terramate create --all-terragrunt
Warning: Dependency outside of Terramate project detected in `dependency.config_path` configuration. Ignoring.
> The Terragrunt module `/terragrunt/dev/a1/b/c/d` depends on the module at  `<the repo path_withouht_repo_root>/a2/b2` (<================ The repo root directory was removed from the path), which is located outside of the your current Terramate project. To resolve this ensure the dependent module is part of your Terramate project.
...
Created stack ...
```

However, it got the warning log and it looks weird as above. (The repo root directory was removed from the path)

Could you check what is happening here, again, please...? 🙏

**Comment by i4ki** [comment]
okay, so this is something else.

Does the error still happens if you run the command from the repository root?
I didn't get an answer if you guys are using `git submodules` or not.

It would be great if you can create a very simple repository that just reproduces this.

**Comment by LittleWat** [comment]
Hi @i4ki Thank you for your reply!

> Does the error still happens if you run the command from the repository root?
No, it succeeded.

- However, this is related to my previous request (https://github.com/terramate-io/terramate/issues/1966), I would like to run the command at ``terragrunt/dev` dir to specify the tag in the future.

>I didn't get an answer if you guys are using git submodules or not.
 I don't use the `git submodules`.
 
 > It would be great if you can create a very simple public repository that just reproduces this.
I made a sample repo to reproduce this: 
- https://github.com/LittleWat/terramate-bug-reproduce/tree/main

(Sorry, actually, this does not get the warning message but the output [stack.tm.hcl](https://github.com/LittleWat/terramate-bug-reproduce/blob/6bef508a6593a31315340bcc73d3dcbdb845839f/terragrunt/dev/a2/b2/c2_2/stack.tm.hcl#L4) looks weird...)

I hope this helps you debug the issue, thank you! 🙇

**Comment by i4ki** [comment]
Thank you very much @LittleWat 

So much easier now! It's indeed a bug, I will fix this ASAP.

**Comment by i4ki** [comment]
hey @LittleWat 

can you check if this PR fixes the problem in your real repository?
https://github.com/terramate-io/terramate/pull/1993

you can install this branch with:
```
go install github.com/terramate-io/terramate/cmd/terramate@i4k-fix-terragrunt-create-deps
```

Thanks for the help!

**Comment by LittleWat** [comment]
@i4ki thank you for addressing this so quickly!! yes, I confirmed this has been fixed, thank you!!

**Comment by LittleWat** [comment]
@i4ki this is a little bit off-topic but I made another issue to ask a beginner question: https://github.com/terramate-io/terramate/issues/1994
I'd be glad if you could reply that 🙏
