### ISSUE TITLE
[Question] the `list --changed` command does not include modules that depend on the changed module. why?

### ISSUE THREAD

**Issue by LittleWat** [terramate-io/terramate#1994]
**Describe the bug**

There is `c2_2` which depends on `c2_3`, but when `c2_3` is updated, `c2_2` does not appear in the results of `terramate list --changed`. Why is that?

I made a sample repo for this: https://github.com/LittleWat/terramate-bug-reproduce/pull/1

**Comment by i4ki** [comment]
Hi @LittleWat,

That's how Terramate works by default and we do this do reduce the blast radius of changes.
If you wish to force a hard dependency between stacks, you can use the `stack.wants` feature. See here: https://terramate.io/docs/cli/stacks/configuration#forced-execution

The point is that most of the time, if you change the dependency of other stack, their state IDs are kept the same and most of the time you don't need to re-apply the ones that depend on it. If you choose to re-apply them, most of the time you will get an empty plan, but there's a risk of a change in a stack that is a dependency of thousands of other stacks to reapply a whole lot of infrastructure, which can lead to undesirable down times or worse. So we advocate that if you change something that you are sure requires re-apply of others you can either `terramate experimental trigger` them in the same PR or (if this is needed all the time) use the `stack.wants` (or `stack.wanted_by`) feature.

**Comment by soerenmartius** [comment]
Hey @LittleWat, let us know if that answers your questions. As mentioned by @i4ki to enforce dependencies that does not contain changes when using change detection, you can use `wants` and `wanted_by` to configure those!

I am closing this question for now. Feel free to reopen in case you have additional input or feedback.

Thanks
