### ISSUE TITLE
[FEATURE] Exclude stacks on `terramate run`

### ISSUE THREAD

**Issue by amemni** [terramate-io/terramate#2023]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When running `terramate list --changed` to list stacks with infrastructure changes, or `terramate run` to plan or apply these infrastructure changes from a GitHub workflow or a similar CI, it will be nice to have a way to filter out specific stacks or folders that shouldn't be targeted with Terramate for different kind of reasons (like circular dependencies or restricted/privileged stacks..etc).

**Describe alternatives you've considered**
An option like `--exclude` would make sense, or `--include`, to exclude and/or include specific stacks (or sub-directories).

**Additional context**
N/A

**Comment by amemni** [comment]
Sorry, we just figured out we can use ´--tags´ and ´no-tags´ to filter out stacks, which solves the problem.

**Comment by amemni** [comment]
Sorry, we just figured out we can use ´--tags´ and ´no-tags´ to filter out stacks.

**Comment by soerenmartius** [comment]
Hi @amemni, great that you figured out how to use tags to exclude specific tags from the orchestration. Currently, the following filters are available and be combined also:

`--changed` - to filter for changed stacks only
`--tags` and `--no-tags` to filters for tags / no tags
`--chdir` to filter for stacks in a specific directory

We will add more filters in the future, for examples `labels` are on the short term roadmap
