### ISSUE TITLE
[FEATURE] - Add in doc a comparison with pro and cons with other tools 

### ISSUE THREAD

**Issue by gillg** [terramate-io/terramate#342]
**Describe the solution you'd like**
I would be able to fully understand key concepts differences between terramate and other well known tools like terragrunt.

**Additional context**
Because terramate approach seems interesting I would understand how you inject vars to terraform with different scopes and what should be versionned on git in stacks folders.

**Comment by soerenmartius** [comment]
Hi @gillg,

Thanks for requesting the comparison. We will come up with a comparison of Terramate and other tools such as Terragrunt, Terraspace, etc,

> Because terramate approach seems interesting I would understand how you inject vars to terraform with different scopes and what should be versionned on git in stacks folders.

Sure, let me take of this!

**Comment by soerenmartius** [comment]
Hi @gillg, we just released a new article in our blog that compares Terramate and Terragrunt https://blog.mineiros.io/terramate-and-terragrunt-f27f2ec4032f

**Comment by gillg** [comment]
Awesome! It helps to clarify your mindset and shows a great analysis :) 
In practice combining terramate and terragrunt remain a little bit abstract but it gives some ideas

**Comment by kitos9112** [comment]
Hi. Is there any update with regards to that comparison matrix yet? We heavily use terragrunt at my company and would like to think of ways to either replace it or enhance it with this tool.

**Comment by soerenmartius** [comment]
> Hi. Is there any update with regards to that comparison matrix yet? We heavily use terragrunt at my company and would like to think of ways to either replace it or enhance it with this tool.

Hi @kitos9112, we've create a matrix internally already - let me check back in with the team to see if we can share this with you already. Will get back to you asap.

**Comment by kitos9112** [comment]
Many thanks @soerenmartius

**Comment by soerenmartius** [comment]
> Hi. Is there any update with regards to that comparison matrix yet? We heavily use terragrunt at my company and would like to think of ways to either replace it or enhance it with this tool.

Hey @kitos9112,

Sorry for letting you wait. We will need a bit more time to finish this but you can expect this to be shipped in September. I will come back to you once we finished it! Again, sorry for the delay!

**Comment by RohanMishra315** [comment]
Hey @soerenmartius is this still open , btw could you provide you blog on comparison btw terramate and other tools.

**Comment by soerenmartius** [comment]
Hi @RohanMishra315 , that's a fair point and I will make up for it during the next few days. Are there any specific tools that you would like to see covered here?

**Comment by RohanMishra315** [comment]
Tools like Terragrunt,Terraspace and Terraplate comparison should covered.BTW , could you tell some issues that I can contribute to.

**Comment by soerenmartius** [comment]
> Tools like Terragrunt,Terraspace and Terraplate comparison should covered.BTW , could you tell some issues that I can contribute to.

Hi @RohanMishra315 , ok I will take care of it :) In a nutshell: Terramate is multi-IaC, Terramate is not a wrapper but an executor - it doesn't require you to move out of native Terraform if you use it to manage Terraform in Terramate Stacks. I'll update this issue when we published the new page
