### ISSUE TITLE
[FEATURE] Allow globs on import

### ISSUE THREAD

**Issue by a-ferri** [terramate-io/terramate#649]
It would be nice to use globs to import modules.

Since my current setup counts with many files on each "stack" that I have, I could easily wrap the file contents into a `generate_hcl` block and just import everything (as is) to my stacks instead of adding many import blocks.

example:
```
modules/
└── my_mod/
    ├── data.tm
    ├── iam.tm
    ├── locals.tm
    └── main.tm
```
```hcl
import {
  source = "/modules/my_mod/*.tm"
}
```

> I know that I can wrap everything into a single file or just add many import blocks, so it's a "nice to have" feature!

**Comment by katcipis** [comment]
Hi @a-ferri,

We are also discussing importing entire directories, but for now we are focusing on other features. As soon as we have any news on this topic we will let you know.

Thanks for taking the time to give feedback :100:

**Comment by a-ferri** [comment]
Working smoothly! Thanks @brk3
