### ISSUE TITLE
[FEATURE] Cannonical Example Repo

### ISSUE THREAD

**Issue by donovanrost** [terramate-io/terramate#968]
**Is your feature request related to a problem? Please describe.**
I have taken over a project using Terramate. I don't believe the previous engineer did it well since the blast radius is huge. I'm still trying to wrap my head around the tool while trying to refactor into smaller modules

**Describe the solution you'd like**
I would like a well designed sample repository that illustrates Terramates opinion on stack design
 
**Describe alternatives you've considered**
Moving off terramate and going to Terragrunt

**Comment by soerenmartius** [comment]
Hi @donovanrost,

Thanks for reaching out. We're about to publish a series of new guides explaining the usage and sizing of stacks for reference architectures in AWS and Google Cloud. In general, stacks should be sized as small as possible. We recommend you group infrastructure resources by business domains also. Let's assume that you want to deploy a network, a Kubernetes cluster and a database. Those would all belong in separate stacks whereas the node groups of the cluster could be managed in a child stack within the Kubernetes stack. You can find an example for Google Cloud in https://github.com/terramate-io/terramate-example-code-generation

I will update this Issue once we release the new guides.

In the meantime, please feel free to join our [Discord](http://terramate.io/discord) to get in touch with our team to help you directly.

**Comment by soerenmartius** [comment]
Hey @donovanrost,

Just wanted to follow up and let you know that I started working on some a reference architecture in https://github.com/terramate-io/terramate/pull/974. I'll complete that example and publish a guide late next week.

Have a good weekend,
Soren

**Comment by soerenmartius** [comment]
Hi @donovanrost good things sometimes take a while! You can now find the reference architecture at https://github.com/terramate-io/terramate-quickstart-aws
